policy:
  approval:
    - or:
      - owners can approve
      - dependabot updates

# the list of rules
approval_rules:
  - name: owners can approve
    requires:
      count: 1
      users: ["josephktcheung"]
  - name: dependabot updates
    if:
      has_labels:
        - "dependencies"
    requires:
      count: 0
