policy:
  approval:
    - or:
      - dependabot updates

# the list of rules
approval_rules:
  - name: dependabot updates
    if:
      has_labels:
        - "dependencies"
    requires:
      count: 0
