sudo: required
services:
  - docker

before_install:
  - docker build -t josephktcheung/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true josephktcheung/docker-react yarn test --coverage
