on: [push]

jobs:
  dropbox:
    runs-on: ubuntu-latest
    name: Sync to dropbox
    steps:
    - name: Sync
      id: sync
      uses: josephktcheung/github-action@1.0.2
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}